### PR TITLE
start sorting with float, fallback to string

### LINKED ISSUE #43: Sorting of indices is done alphabetically, not numerically
The example gives an index in the form of a float as a string (`'1.1'`), but then components are sorted by index alphabetically using `localeCompare`.  This has the effect of limiting indexes to 10 top level categories, at least using the format of the current example.

This can be fixed by first attempting to sort with the `parseFloat()` of the indices when they are both parseable, otherwise, fall back to a localeCompare.  Sorting also tends to be more logical if a check for two missing indices occurs before the current comparison and returns a `0`.

### PR DESCRIPTION
**Pull request by bendman**
This fixes #43

### CODE REVIEW

**Comment by theogravity** [comment]
Looks good to me.

Please make sure the changelog is updated and publish under minor level

**Comment by bendman** [comment]
Okay, thanks

**Comment by bendman** [comment]
done, v3.9.0 shipped!

**Comment by theogravity** [comment]
thanks!

**Pull request merged**
