### PR TITLE
Adding webpack url-loader to webpack config

### PR DESCRIPTION
**Pull request by mattdell**
This is a fix solution for #51

### CODE REVIEW

**Comment by bendman** [comment]
Isn't it possible to pass in your own `webpackConfig` passed into RSG?  Then you can just add url-loader  externally.

It seems like a slippery slope to require RSG to internally depend on every loader someone might need in their own code, when you can just pass loaders in as a configuration variable.  This is helped by webpack's manner of resolving loaders relative to the input file, not relative to the config.

**Comment by theogravity** [comment]
I have to agree - we shouldn't be adding loaders willy-nilly. It should be added to your own webpackConfig instead.

**Comment by mattdell** [comment]
I wasn't aware we could send our own webpack config. This would have prevented my previous pull request for #33.

**Comment by theogravity** [comment]
The i think the prev one is fine - i also use json-loader myself, and i'm unsure if there is another json-type loader that others would use

**Pull request closed without merging**
