### PR TITLE
Upgrade to babel 6.4 (fixes #9)

### LINKED ISSUE #9: Babel 6.4 semicolon problem
Hi,

Thanks for the help. The trace is (is there any way to beautfify this?):
```
> node_modules/rsg-alt/bin/rsg containers/App.js

{"name":"rsg/rsg-lib","hostname":"sapobook","pid":93843,"level":50,"msg":"[ './~/rsg-alt/app/components/App/index.js\\nModule build failed: SyntaxError: /Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/rsg-alt/app/components/App/index.js: A semicolo
n is required after a class property (7:31)\\n\\u001b[0m   5 | \\n   6 | \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mclass\\u001b[39m App \\u001b[36mextends\\u001b[39m Component \\u001b[32m{\\u001b[39m\\n>  7 |   static displayName \\u001b[1m=\
\u001b[22m \\u001b[31m\\'SG.App\\'\\u001b[39m\\n     |                                ^\\n   8 | \\n   9 |   static propTypes \\u001b[1m=\\u001b[22m \\u001b[32m{\\u001b[39m\\n  10 |     ctx\\u001b[1m:\\u001b[22m PropTypes\\u001b[1m.\\u001b[22mobject\\u001b[1m.\\u001b[22
misRequired\\u001b[0m\\n    at Parser.pp.raise (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:1413:13)\\n    at Parser.pp.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:
2565:10)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Pa
rser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.pp.parse
ClassBody (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2470:34)\\n    at Parser.pp.parseClass (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2413:8)\\n    at Parser.pp.parseExport (/User
s/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2630:19)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3625:20)\\n @ ./~/rsg-alt/app/index.js 15:11-38' ]","time":"201
6-01-08T19:46:41.470Z","v":0}
```

My package.json is:

```
{
  "name": "react-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js test/**/*.spec.js",
    "test:cov": "NODE_ENV=test babel-node node_modules/isparta/bin/isparta cover --report text --report html node_modules/mocha/bin/_mocha -- --recursive --compilers js:babel-register --require ./test/setup.js test/**/*.spec.js",
    "test:watch": "npm test -- --watch",
    "start": "webpack-dev-server",
    "check": "npm-check -s",
    "check:u": "npm-check -u",
    "lint": "eslint .",
    "lint:fix": "eslint --fix .",
    "build": "ENV=production webpack --config webpack.prod.config.js",
    "styleguide": "node_modules/rsg-alt/bin/rsg containers/App.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "~6.3.17",
    "babel-core": "~6.3.26",
    "babel-eslint": "^4.1.6",
    "babel-loader": "^6.2.1",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-rewire": "^1.0.0-beta-3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "~6.3.0",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.3.13",
    "babel-runtime": "^6.3.19",
    "css-loader": "^0.23.1",
    "es3ify-loader": "^0.1.0",
    "eslint": "^1.10.3",
    "eslint-config-airbnb": "^2.1.1",
    "eslint-plugin-mocha": "^1.1.0",
    "eslint-plugin-react": "^3.14.0",
    "expect": "^1.13.4",
    "isparta": "^4.0.0",
    "jsdom": "^7.2.2",
    "mocha": "^2.3.4",
    "node-bourbon": "^4.2.3",
    "node-sass": "^3.4.2",
    "npm-check": "^4.1.3",
    "react-styleguide-generator": "^1.2.1",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "rewire": "^2.5.1",
    "rsg-alt": "^3.1.0",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.10",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-dev-server": "^1.14.0",
    "webpack-hot-middleware": "^2.6.0"
  },
  "dependencies": {
    "history": "^1.17.0",
    "lokka": "^1.6.1",
    "lokka-transport-http": "^1.3.0",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-redux": "^4.0.6",
    "react-router": "^1.0.3",
    "redux": "^3.0.5",
    "redux-form": "^4.1.1",
    "redux-logger": "^2.3.1",
    "redux-simple-router": "^1.0.2",
    "redux-thunk": "^1.0.3"
  }
}
```

This is my App.js:
```
const React = require('react');
const { Component } = React;

const FormContainer = require('./FormContainer');
const ProductLinkContainer = require('./ProductLinkContainer');

module.exports = class App extends Component {
  static styleguide = {
    index: '1.1',
    category: 'components',
    title: 'App',
    description: 'Some **App**',
    code: '<App />',
    className: 'css class'
  };

  render() {
    return (
      <div>
        <FormContainer />
        <ProductLinkContainer />
      </div>
    );
  }
};
```

`npm ls | grep babel | grep 6.4`:
```
│ ├─┬ babel-generator@6.4.2
│ ├─┬ babel-helpers@6.4.0
│ ├─┬ babel-types@6.4.1
│ ├─┬ babelify@6.4.0
```

### PR DESCRIPTION
**Pull request by gregz67**
Upgrades to babel 6.4 and corrects missing static class variable semicolons.

I found that I needed to make this change in order to use the `rsg-alt` package in a project that was using babel 6.4.  Is there some other way to isolate the babel version in rsg?

### CODE REVIEW

**Comment by theogravity** [comment]
Thanks for the contrib, @gregz67. Your changes look good to me, but one issue...

Does this cover the issue with using `standard`? For people using `standard`, the semicolons won't pass the linter. 

See: https://github.com/feross/standard/issues/372

I do not have any immediate ideas on version isolation, but am completely open.

Will add you as a contrib with npm publish rights after we make sure it doesn't break for `standard` users

**Comment by theogravity** [comment]
It looks like the semicolon on class props requirement may get reverted according to https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-171587367

**Comment by theogravity** [comment]
Also missing the entry to HISTORY.md as well. I use https://github.com/defunctzombie/changelog to update it. Just do `changelog --increment` and add in your changes to it. Do not do `changelog --release`, just leave the `UNREALEASED` message for now. Can do `changelog --release` after merging in.

**Comment by gregz67** [comment]
I will research the status of semicolon requirements from jeffmo. And test
with standard. It may be this PR should not be merged to master. Maybe to a
branch specific to babel 6.4?  I'll also update history.

**Comment by theogravity** [comment]
I'd be okay with a branch, but hesitant on doing any kind of publish

**Comment by theogravity** [comment]
i've given you collab rights - feel free to create a `babel-6.4` branch and push to that. Can update the readme on master to point people to the 6.4 branch.

Wish it wasn't so ugly. Hopefully babel ends up reverting or standard makes an exception.

**Comment by flying-sheep** [comment]
> It looks like the semicolon on class props requirement may get reverted

will be reverted, see [here](https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-177720642)

it was simply a misunderstanding about the semicolon in the grammar definition: it means that the semicolon can be there literally, or be inserted by ASI. i.e. it’s not required in non-ambiguous cases, and the babel commit will be reverted.

**Comment by theogravity** [comment]
Thanks. Let's wait until it's reverted before we put it into mainline. If it's absolutely needed, can make the `babel-6.4` branch and then merge into main when the revert happens (although I'm sure it'll be a different version eg 6.5 by then)

**Comment by gregz67** [comment]
Closing this PR.  I have created a shrinkwrap to pin to `babylon@6.3.26`

@flying-sheep what is the target babel release for the revert?

**Comment by flying-sheep** [comment]
no idea, all info i have is in the linked comment. you’ll have to ask @jeffmo and the babel maintainers

**Pull request closed without merging**
