### PR TITLE
FIxes #53 fix to render also pure function components

### LINKED ISSUE #53: document functional components
Hi

Here is an example of a react functional component : 

```
const Header = ({content}) => {
    return (
        <header className="topbar">
         {content}
        </header>
    );
};
```

Can you tell me if it is possible to document such a component ?

Best regards

### PR DESCRIPTION
**Pull request by ticemochka**

### CODE REVIEW

**Comment by theogravity** [comment]
Thanks for the PR, it looks shippable to me. Before I give you merge perms, can you please update the HISTORY.md via this process:

I use https://github.com/defunctzombie/changelog to update it. Just do changelog --increment and add in your changes to it. Do not do changelog --release, just leave the UNREALEASED message for now. Can do changelog --release after merging in.

Also need your npm username

**Comment by ticemochka** [comment]
npm name same as github  :)

**Comment by theogravity** [comment]
You're good to merge and publish - update under minor version please

**Comment by theogravity** [comment]
Don't forget to `changelog --release <version>`, push, and `npm publish` after

**Comment by ticemochka** [comment]
yes, thanks for the reminder

**Pull request merged**
