### PR TITLE
Bump babel to 6.5.2

### PR DESCRIPTION
**Pull request by gregz67**
Hey @theogravity 

I think this is what you are looking for.  I've moved to babel 6.5.2 or higher.  I also removed the unnecessary babylon dependency as it comes from babel.

### CODE REVIEW

**Comment by theogravity** [comment]
Don't forget to update the changelog then :ship:  and publish.

Thanks!

**Comment by theogravity** [comment]
Fixes https://github.com/theogravity/react-styleguide-generator-alt/issues/9

**Comment by gregz67** [comment]
:+1: All set.  Published 3.3.0

**Comment by theogravity** [comment]
Thanks!

**Pull request merged**
