### PR TITLE
Setting redbox react version to specific 1.2.6

### LINKED ISSUE #54: Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.
I've got this error all of the sudden this morning:

```
Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.
```

I've recently updated my node_modules. Anyone else?

screen shot 2016-06-21 at 16 52 25

### PR DESCRIPTION
**Pull request by mattdell**
Fixes #54

### CODE REVIEW

**Comment by theogravity** [comment]
May I ask you to fix each package ver as well?

**Comment by mattdell** [comment]
You mean like...

```
  "dependencies": {
    "babel-core": "6.5.2",
    "babel-loader": "6.2.2",
    "babel-plugin-react-transform": "2.0.0",
    "babel-preset-es2015": "6.5.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-stage-0": "6.5.0",
    "bunyan": "1.4.0",
    "css-loader": "0.23.0",
    "cssnext": "1.7.1",
    "cssnext-loader": "1.0.1",
    "deepmerge": "anthonator/deepmerge#feature/array-options",
    "express": "4.13.3",
    "fs-extra": "0.24.0",
    "glob": "5.0.10",
    "highlight.js": "9.0.0",
    "immutable": "3.7.5",
    "json-loader": "0.5.4",
    "marked": "0.3.3",
    "minimist": "1.1.1",
    "mustache": "2.1.2",
    "object-assign": "4.0.1",
    "page": "1.6.4",
    "react-bootstrap": "0.27.1",
    "react-docgen": "2.0.0",
    "react-simpletabs": "matthewgertner/react-simpletabs",
    "react-transform-catch-errors": "1.0.0",
    "react-transform-hmr": "1.0.1",
    "redbox-react": "1.2.6",
    "slash": "1.0.0",
    "style-loader": "0.13.0",
    "webpack": "1.12.9",
    "webpack-dev-middleware": "1.4.0",
    "webpack-hot-middleware": "2.6.0",
    "promise": "~7.1.1"
  },
  "devDependencies": {
    "babel-eslint": "4.0.5",
    "eslint-plugin-react": "3.10.0",
    "gh-pages": "0.4.0",
    "mocha": "2.2.5",
    "react": "0.14.3",
    "react-dom": "0.14.3",
    "rimraf": "2.4.0",
    "standard": "5.4.1",
    "uglify-js": "2.4.23"
  }
```

?

**Comment by theogravity** [comment]
yep, ship with that if it works

**Comment by theogravity** [comment]
🚢 , prob patch level is fine

**Comment by mattdell** [comment]
Done. Let me know if that works for you. Have also done it on #56.

**Comment by mattdell** [comment]
Will do

**Comment by theogravity** [comment]
thanks dude!

**Pull request merged**
