### PR TITLE
Fixes #58 issue to use hmr w/o errors

### LINKED ISSUE #58: There is an error in rsg -d
If try to run --dev version there is error `vendor.bundle.js:1 Uncaught SyntaxError: Unexpected token <`

### PR DESCRIPTION
**Pull request by grammka**
Fixed wrong path to 'publicPath' variable from webpackConfig

### CODE REVIEW

**Comment by theogravity** [comment]
looks good to me, please follow

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/CONTRIBUTING.md

to update HISTORY.md and give me your npm username

**Comment by grammka** [comment]
@theogravity hi, I pushed HISTORY.md changes, and my npm name is **grammka**

**Comment by theogravity** [comment]
hey there, not seeing it in the commit?

**Comment by theogravity** [comment]
anyways, ive added you in - please make sure the HISTORY.md is included before merging

**Comment by grammka** [comment]
@theogravity thx, check my last commit

**Comment by theogravity** [comment]
still not seeing it under https://github.com/theogravity/react-styleguide-generator-alt/pull/59/files

**Comment by theogravity** [comment]
ah, i see it in master - next time please make sure it's included with the existing PR

**Comment by grammka** [comment]
@theogravity ok, sry)

**Comment by theogravity** [comment]
feel free to merge this one in, please `changelog --release <version>`, push then publish under minor version

**Comment by grammka** [comment]
@theogravity I'd like to chat with u if you do not mind. I wrote u email, check it pls

**Comment by theogravity** [comment]
I don't mind - can you message via Google hangouts theo@suteki.nu? I might not be able to respond immediately but will when I'm available

**Pull request merged**
