### PR TITLE
Updated deepmerge in package.json to use npm

### LINKED ISSUE #72: Git errors during npm install
I'm unable to install the package due to git errors relating to this dev dependency in the package.json:

"deepmerge": "anthonator/deepmerge#feature/array-options",

Could it point to the deepmerge package on npm now as it seems up to date with the fork e.g.

"deepmerge": "0.2.10"

This article (https://circleci.com/docs/git-npm-install/) suggests that if a dependency points to a github repo it should use the full https:// address.

### PR DESCRIPTION
**Pull request by iblack10**
Fixes #72

### CODE REVIEW

**Comment by theogravity** [comment]
Thanks. Before I can accept it, please follow the contrib guidelines in the root of the project

**Comment by iblack10** [comment]
Apologies! At the moment I can't install changelog (similar reason to why I created the actual pull request!) so I'll need to do this later on a different network.

**Comment by theogravity** [comment]
np

**Comment by iblack10** [comment]
Sorry, I still can't get the changelog package to install from a github repo.

**Comment by theogravity** [comment]
I don't mind doing it, but I'm unable to verify where the 0.2.10 ver comes from 

I'm looking at https://github.com/KyleAMathews/deepmerge, which the npm package points to

**Comment by iblack10** [comment]
It looks like https://github.com/anthonator/deepmerge#feature/array-options is a fork of KyleAMathews/deepmerge and it says the two are even.

**Comment by theogravity** [comment]
It looks like the author forgot to publish a new package.json with 0.2.10 but the commit tag shows 0.2.10.

I also looked at the change history for that ver and it's just a license update. 

This is the diff between the custom ver we use vs the orig author, which doesn't seem to be merged in:

https://github.com/KyleAMathews/deepmerge/compare/KyleAMathews:master...anthonator:feature/array-options?expand=1

My recommendation is, fork the custom repo and publish an alt version eg `deepmerge-alt`

**Comment by iblack10** [comment]
Not sure  I'm comfortable owning and maintaining a fork of deepmerge just now. Reading into it it looks like they are in favour of deprecating it and suggesting loadash's merge function instead...

I'm actually not sure the style guide generator will work in my use case (wrapping of exported classes with connect() for redux) but wanted to spin it up and see.

**Comment by theogravity** [comment]
I don't mind doing the fork and publshing

**Comment by iblack10** [comment]
Much appreciated. Trying to figure out why I can't npm install straight from a github repo - assuming it's not just me that has this problem!

**Comment by theogravity** [comment]
done

**Pull request closed without merging**
