### PR TITLE
changes dynamic nav links to route to an absolute path

### LINKED ISSUE #39: pushstate breaks sidebar navigation
It looks like sidebar navigation using pushstate doesn't work. Navigation just doesn't seem to function at all. You can see this in the official included example styleguide.

1. Open `example/styleguide.json`
2. After line 6, add a line:  `"pushstate": true`
3. `npm run`
4. Navigate to localhost:3000
5. Click any sidebar link, for example "Buttons"  

6. Click any other sidebar link, for example "Button dropdowns"  

7. Repeat.

@bendman and I are starting work on it now. Not sure what the deal is.

### PR DESCRIPTION
**Pull request by joefraley**
Fixes #39

### CODE REVIEW

**Comment by theogravity** [comment]
thanks, does this also work when pushState is false?

**Comment by joefraley** [comment]
Thanks @theogravity, it sure doesn't. I'll patch it up, should be a quick fix. Just have to check for window.config.hashbang.

**Comment by joefraley** [comment]
npm username: joefraley

I'm not sure how you feel about depending on the `window.config` variable here instead of passing it down as props. It feels like the sort of variable that should be set as state, but this check for `window.config.hashbang` is consistent with other global expectations in the file.

**Comment by theogravity** [comment]
i'm indifferent - 🚢 

see for merge instructions - or ask @bendman  since you seem to be working with him(?)
https://github.com/theogravity/react-styleguide-generator-alt/pull/35

**Comment by joefraley** [comment]
Yup, we work together at Idealist.org 😄

**Comment by theogravity** [comment]
Nice! looks like a good alternative to linkedin jobs for non-tech

**Comment by mattdell** [comment]
Have you explored getting this to work in the 2x version?

**Comment by theogravity** [comment]
not really mainly because it works for us on our end with the current 2x ver

**Pull request merged**
